:toc: left
:numbered:
:toclevels: 2
:sectlinks:
:project_name: uml-unittest-generator

= uml-unittest-generator

[options="header"]
[cols="1, 3, 3"]
|===
|Version | Processing Date   | Author 
|0.2	| November 29th, 2019 | Daniel Schoenicke 
|===

== Context
* Task description

[#constraints]
== Constraints
* Definition of constraints for the input diagrams

== Architecture
[caption="Figure 1: Top Level Architecture"]
image:diagrams/top-level-diagram.svg[top level architecture]

The project _{project_name}_ is a Maven parent project, which consists
of the _core_-module and additional modules of input representations and converters, 
as well as output converters. +
The _core_ module contains the three representations (_Uml, Code, Test_), which are
Maven modules themselves, and the two converters for these representations. The representations
abstract an input diagram step-by-step to an output format. +

For more information on the representations, see chapter <<#representations>>. + 
For more information on the converters, see chapter <<#converters>>.

_Representation-uml_ acts as an interface for input diagrams, to which an input representation
needs to be converted (see <<#input>> for a description of the _input-mdxml-representation_ and _input-mdxml-converter_). +
To generate an output other than _jUnit Structure Tests_, another output converter using _representation-test_
as input needs to be implemented (see <<#output>> for a description of the _test-junit-converter_).

[#representations]
== Representations
During the conversion process, the input diagram is converted
to several representations before an output is generated. The following section contains descriptions
of each of these representations and references to their respective javadocs.

=== UML-Representation
The UML representation presentation acts as the first abstraction of the input class diagram within
the application. The diagram representation of a modeling tool has to be converted to this representation
in a first step. Therefore, the UML representation provides an interface for a converter, which converts
a diagram representation of a modeling tool to the UML representation.

==== Package: uml
link:javadoc/uml/package-summary.html[Javadoc of the uml package]

The uml package contains all model classes of the representation. The representation has a tree structure
with an instance of _UmlModel_ as the root node. The _UmlModel_ holds lists of _UmlElements_ and _UmlRelationships_,
which are not assigned to a package. Furthermore it holds a list of _UmlPackages_, which contain _UmlElements_, _UmlRelationships_
and _UmlPackages_.

_UmlElement_ is an abstract class, which is extended by _UmlClass_, _UmlInterface_ and _UmlEnumeration_. These three subclasses
are distinguished by their non access modifiers. Furthermore, _UmlEnumerations_ have a list of _UmlLiterals_.

_UmlElements_ have a list of _UmlAttributes_ and _UmlOperations_, as well as lists of _UmlTemplateBindings_ and _UmlTemplateParameters_.
The enumeration _UmlVisibility_ determines the access modifier of _UmlElements_, _UmlAttributes_ and _UmlOperations_. The _UmlParameters_
of _UmlOperations_ have a direction, determined by the _UmlParameterDirection_ - enumeration, which helps to distinguish input- and return parameters. 
Furthermore, the multiplicity of _UmlAttributes_ and _UmlParameters_ is determined by the _UmlMultiplicityValue_ - enumeration, which describes
the upper and lower value of the multiplicity.

_UmlTemplateBindings_ have one or more _UmlParameterSubstitution_, which maps the type of the substitute to the corresponding _UmlTemplateParameter_.

Relationships are described by an _UmlRelationship_ object, which has a client and a supplier, both as a reference to an _UmlElement_. If the relationship
is undirected, the assignment of client and supplier is arbitrary. The type of the relationship is determined by the _UmlRelationshipType_ - enumeration.

==== Package: uml.converterinterface
link:javadoc/uml/converterinterface/package-summary.html[Javadoc of the uml.converterinterface package]

This package contains an interface, which defines a conversion method, that returns the converted _UmlModel_ out of a given _UmlInputRepresentation_.
The _UmlInputRepresentation_ - interface needs to be implemented by the root object of the input representation to be converted.

=== Code-Representation
link:javadoc/code/package-summary.html[Javadoc of the code package]

The code representation aims to provide compatibility to the Java Reflection API. The representation contains no relationships, as they are implicated
via the class fields and references to super classes and interfaces, which is held by each _CodeElement_. 

Furthermore, the modifiers of a _CodeElement_, _CodeField_, _CodeMethod_ and _CodeParameter_ are represented by an
integer value calculated in the same way, as Java Reflection does (see: link:https://docs.oracle.com/javase/8/docs/api/constant-values.html#java.lang.reflect.Modifier.ABSTRACT[List of java.reflect.Modifier enum constants]).
Therefore, the class _CodeModifier_ extends the class java.lang.reflect.Modifier and adds a method to calculate the integer modifier
out of a _CodeVisibility_ and boolean values for the _static_, _final_ and _abstract_ modifier.

While the UML representation can contain _CodeElements_ at the top level without a _UmlPackage_, the _CodeElements_ without a package in the diagram
are grouped into a _CodePackage_ with the name of the model.

=== Test-Representation
link:javadoc/test/package-summary.html[Javadoc of the test package]

The test representation represents the structure of the test suite to be created. It consists out of a _TestRepresentation_ as root element, 
which has the name of the project and a list of _TestPackages_. The package structure should be consistent to the package structure of the implementation,
which will be checked. _TestPackages_ contain sub _TestPackages_ and _TestClasses_. Each _TestClass_ represents a _CodeElement_ which will be tested in the class.
The _TestClass_ contains _TestMethods_ which are the actual methods executed in the test runs. _TestMethods_ will be created for each field, constructor and method
of an element. 

_TestMethods_ contain a list of _TestAssertions_ which are the actual assertions to be checked in the method. _TestAssertions_ have a _TestAssertionType_, 
which determines the type of assertion to be used, to implement the _TestAssertion_ in the actual test method.

[#converters]
== Converters
* Descriptions of all the converters

=== converter-uml-code

=== converter-code-test

[#input]
== Input
To use the _{project_name}_, an input class diagram has to be converted to the _UML representation_. +
This requires at least the implementation of a converter and possibly a representation of the input diagram. + 
This chapter describes on the example of the _input-mdmxl-representation_ and _input-mdxml-converter_, 
how such a representation and converter can be implemented.

=== input-mdxml-representation
link:../javadoc/mdxml/package-summary.html[Javadoc of the mdxml package]

MagicDraw provides the ability to save projects in an XML file. As a first step, this XML representation is converted into
the _input-mdxml-representation_ by unmarshalling the XML elements to Java objects with link:https://github.com/eclipse-ee4j/jaxb-ri[JAXB]. +
This conversion doesn't transform the elements of the XML file, it only leaves out some superfluous elements and attributes, which aren't
needed for the conversion to the _UML representation_. +
As described in the <<#constraints>> section, an input model must only describe one coherent application. Therefore, information about the separate
diagrams of the project is discarded. +
The whole _input-mdxml-representation_ is a tree structure, like all the other <<#representations>>. The root class _MdxmlRepresentation_ takes the
path to the XML file as an argument in its constructor, where it initializes the JAXB environment. This root class implements the link:javadoc/uml/converterinterface/UmlInputRepresentation.html[UmlInputRepresentation]
interface, provided by the _UML Representation_, which is necessary for the _input-mdxml-converter_.

=== input-mdxml-converter
link:../javadoc/mdxmlconverter/package-summary.html[Javadoc of the input-mdxml-converter]

A converter converting an input representation to the _UML representation_ must have a central class implementing the link:/javadoc/uml/converterinterface/UmlRepresentationConverter.html[UmlRepresentationConverter] interface
with its _convertToUmlRepresentation_ method. This method requires an object of type _UmlInputRepresentation_ which should be the root class of the input representation.
This method acts as the main conversion method and must return an converted _UmlModel_. 

Besides this class, the _input-mdxml-converter_ consists out of four packages, which contain converters for modifiers, elements (with their attributes, methods, template parameters, etc.), relationships and packages,
as well as the package _mdxmlconverter.temporary_, which contains auxiliary classes to store the ids used by MagicDraw's XML representation to reference other elements, relationships, etc. During the conversion of each part of the 
representation, the converted object is stored with its corresponding mdxml-id in a map, which is later used to resolve these references and replace mdxml ids with the actual objects.

=== Summary - How to write an input converter
To convert an uml class diagram to the _UML representation_ follow these steps:

* Model the diagram according to the defined <<#constraints>>.
* Transform the project into a representation with a root class implementing the _UmlInputRepresentation_ interface.
* Implement a converter using the _UmlRepresentationConverter_ interface to convert the input representation to the _UML-representation_.

[#output]
== Output
* Description of how to implement an output representation and converter

== Tests
* Description of the test strategy
